theme: jekyll-theme-cayman
google_analytics_id: UA-100373569-2

name: NEAR.AI
title: NEAR.AI
tagline: AI is near Near.ai
description: Working on cutting edge Machine Learning to bring AI closer
url: http://near.ai

