theme: jekyll-theme-cayman
google_analytics_id: UA-100373569-2

name: Near.ai
title: Near.ai
tagline: Cutting edge Machine Learning to bring AI closer
description: Working on cutting edge Machine Learning to bring AI closer
url: https://near.ai

